import { Grid } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { IndexStyled } from "../styles";
import { prisma } from "../prisma/prisma";
import { url } from "@prisma/client";
import { tag } from "../src/generated/client";
import ButtonAppBar from "../components/navbar/index.mavbar";

export async function getServerSideProps({ req, res }: any) {
  return {
    props: {
      result: await prisma.tag.findMany({
        select: { url: true, title: true, id: true },
      }),
    }, // will be passed to the page component as props
  };
}
type props = { result: (tag & { url: url[] })[] };
const Home: NextPage<props> = (props: props) => {
  return (
    <>
      <ButtonAppBar />

      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <IndexStyled>
          <Grid container spacing={2}>
            {props.result.map((res) => (
              <Grid item xs={12} sm={6} md={4} lg={3} key={res.id + ""}>
                <Typography
                  variant="h5"
                  style={{
                    borderBottom: "solid black 1.0px",
                    marginBottom: 10,
                  }}
                >
                  {res.title}
                </Typography>
                <Grid container spacing={2}>
                  {res.url.map((res) => (
                    <Grid
                      key={res.id + ""}
                      className="gridItem"
                      item
                      xs={12}
                      sm={12}
                    >
                      <a href={res.url} target={"__blank"}>
                        <Card
                          sx={{
                            maxWidth: 345,
                            display: "flex",
                            justifyContent: "start",
                            alignItems: "start",
                          }}
                          variant="outlined"
                        >
                          <CardMedia
                            component="img"
                            height="70"
                            style={{ width: 100 }}
                            image={
                              res.imgUrl ? "api/add/image/" + res.imgUrl : ""
                            }
                            alt={res.title}
                          />
                          <CardContent style={{ margin: 0, padding: 2 }}>
                            <Typography
                              variant="h5"
                              component="div"
                              fontSize={20}
                            >
                              {res.title}
                            </Typography>
                          </CardContent>
                        </Card>
                      </a>
                    </Grid>
                  ))}
                </Grid>
              </Grid>
            ))}
          </Grid>
        </IndexStyled>
      </div>
    </>
  );
};

export default Home;
