import { Grid } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import { IndexStyled } from "../styles";
import { prisma } from "../prisma/prisma";
import { url } from "@prisma/client";

export async function getServerSideProps({ req, res }: any) {
  return {
    props: {
      result: await prisma.url.findMany(),
    }, // will be passed to the page component as props
  };
}
const Home: NextPage<{ result: url[] }> = (props: { result: url[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexStyled>
        <Grid container>
          {props.result.map((res) => (
            <Grid id={res.id + ""} className="gridItem" item md={3} xs={12}>
              <a href={res.url} target={"__blank"}>
                <Card sx={{ maxWidth: 345 }}>
                  <CardMedia
                    component="img"
                    height="140"
                    style={{ objectFit: "cover" }}
                    image={res.imgUrl ? res.imgUrl.replace("/public", "") : ""}
                    alt={res.title}
                  />
                  <CardContent style={{ margin: 0, padding: 5 }}>
                    <Typography
                      gutterBottom
                      variant="h5"
                      component="div"
                      fontSize={20}
                    >
                      {res.title}
                    </Typography>
                  </CardContent>
                </Card>
              </a>
            </Grid>
          ))}
        </Grid>
      </IndexStyled>
    </div>
  );
};

export default Home;
